{{- if .Values.experimental.localPlugins }}
{{- range $localPluginName, $localPlugin := .Values.experimental.localPlugins }}
{{- if $localPlugin.inlinePlugin }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "traefik.localPluginCmName" (dict "context" $ "pluginName" $localPluginName) }}
  namespace: {{ template "traefik.namespace" $ }}
  labels:
    {{- include "traefik.labels" $ | nindent 4 }}
data:
  {{- range $fileName, $fileContent := $localPlugin.inlinePlugin }}
  {{ $fileName }}: |
    {{- $fileContent | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
